[package]
name = "smartnotes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.5.0"
notify = "6.0.0"
tokio = { version = "1", features = ["full"] }
async-openai = "0.10.3"
